import React, { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import {
  FileText,
  User,
  MapPin,
  CalendarRange,
  FileType,
  Link as LinkIcon,
  ShieldCheck,
} from "lucide-react";
import { apiFetch } from "../../utils/apiConfig";
import { SmartForm } from "../../components/form/SmartForm";
import type { FormSectionConfig } from "../../components/form/SmartForm";
import { FormPageHeader } from "../../components/form/FormPageHeader";

interface ReportFormData {
  _id?: string;
  reportName: string;
  reportType: string;
  generatedBy: string;
  locationFilter: string;
  startDate: string;
  endDate: string;
  fileType: string;
  fileUrl: string;
  status: string;
}

const emptyForm: ReportFormData = {
  reportName: "",
  reportType: "",
  generatedBy: "",
  locationFilter: "",
  startDate: "",
  endDate: "",
  fileType: "PDF",
  fileUrl: "",
  status: "Generated",
};

const toDateInputValue = (value?: string) => {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toISOString().slice(0, 10);
};

export const ReportForm = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const editReport = location.state?.report;
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  const [formData, setFormData] = useState<ReportFormData>(
    editReport
      ? {
          ...emptyForm,
          ...editReport,
          startDate: toDateInputValue(editReport.startDate),
          endDate: toDateInputValue(editReport.endDate),
        }
      : emptyForm
  );

  const handleFieldChange = (name: string, value: any) => {
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setSubmitting(true);

    const {
      _id,
      createdAt: _createdAt,
      updatedAt: _updatedAt,
      ...payload
    } = formData as any;

    try {
      if (editReport?._id) {
        await apiFetch(`/api/v1/reports/${editReport._id}`, {
          method: "PATCH",
          body: JSON.stringify(payload),
        });
      } else {
        await apiFetch("/api/v1/reports", {
          method: "POST",
          body: JSON.stringify(payload),
        });
      }
      navigate("/reports");
    } catch (err: any) {
      setError(err.message || "Failed to save Report");
    } finally {
      setSubmitting(false);
    }
  };

  const sections: FormSectionConfig[] = [
    {
      title: "Report Details",
      description: "What this report is about and who requested it.",
      icon: FileText,
      fields: [
        { name: "reportName", label: "Report Name", type: "text", icon: FileText, required: true, span: 2, placeholder: "e.g. Monthly Tree Plantation Report" },
        {
          name: "reportType",
          label: "Report Type",
          type: "select",
          icon: FileText,
          required: true,
          options: [
            { label: "Tree Report", value: "Tree Report" },
            { label: "Activity Report", value: "Activity Report" },
            { label: "Vehicle Report", value: "Vehicle Report" },
            { label: "Person Report", value: "Person Report" },
            { label: "Mitra Report", value: "Mitra Report" },
          ],
        },
        { name: "generatedBy", label: "Generated By", type: "text", icon: User, required: true, placeholder: "e.g. Admin User" },
        { name: "locationFilter", label: "Location Filter", type: "text", icon: MapPin, placeholder: "e.g. District / Vidhan Sabha name" },
      ],
    },
    {
      title: "Date Range",
      description: "The period of data this report covers.",
      icon: CalendarRange,
      fields: [
        { name: "startDate", label: "Start Date", type: "date", icon: CalendarRange, required: true },
        { name: "endDate", label: "End Date", type: "date", icon: CalendarRange, required: true },
      ],
    },
    {
      title: "Output & Status",
      icon: FileType,
      fields: [
        {
          name: "fileType",
          label: "File Type",
          type: "select",
          icon: FileType,
          required: true,
          options: [
            { label: "PDF", value: "PDF" },
            { label: "Excel", value: "Excel" },
          ],
        },
        { name: "fileUrl", label: "File URL", type: "url", icon: LinkIcon, placeholder: "https://...", helpText: "Optional link to the generated file." },
        {
          name: "status",
          label: "Status",
          type: "select",
          icon: ShieldCheck,
          required: true,
          options: [
            { label: "Generating", value: "Generating" },
            { label: "Generated", value: "Generated" },
            { label: "Failed", value: "Failed" },
          ],
        },
      ],
    },
  ];

  return (
    <div className="dashboard-area">
      <FormPageHeader
        icon={FileText}
        title={editReport ? "Edit Report" : "Generate Report"}
        subtitle="Generate and manage system reports."
        onBack={() => navigate("/reports")}
      />

      <div className="card">
        <SmartForm
          sections={sections}
          formData={formData}
          onFieldChange={handleFieldChange}
          onSubmit={handleSubmit}
          submitting={submitting}
          error={error}
          submitLabel={editReport ? "Update Report" : "Save Report"}
          cancelLabel="Cancel"
          onCancel={() => navigate("/reports")}
        />
      </div>
    </div>
  );
};

export default ReportForm;
