import React, { useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";

export const ReportForm = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const editReport = location.state?.report;

  const [formData, setFormData] = useState(
    editReport || {
      id: "",
      reportName: "",
      reportType: "",
      generatedBy: "",
      locationFilter: "",
      dateRange: "",
      generatedDate: "",
      fileType: "PDF",
    }
  );

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    navigate("/reports");
  };

  return (
    <div className="dashboard-area">
      <div className="page-header">
        <h1>{editReport ? "Edit Report" : "Generate Report"}</h1>
      </div>

      <div className="card">
        <form className="modal-form" onSubmit={handleSubmit}>
          <div className="form-group">
            <label>Report Name</label>
            <input
              name="reportName"
              value={formData.reportName}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label>Report Type</label>
            <select
              name="reportType"
              value={formData.reportType}
              onChange={handleChange}
            >
              <option>Tree Report</option>
              <option>Activity Report</option>
              <option>User Report</option>
              <option>Vehicle Report</option>
            </select>
          </div>

          <div className="form-group">
            <label>Generated By</label>
            <input
              name="generatedBy"
              value={formData.generatedBy}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label>Location Filter</label>
            <input
              name="locationFilter"
              value={formData.locationFilter}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label>Date Range</label>
            <input
              name="dateRange"
              value={formData.dateRange}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label>Generated Date</label>
            <input
              type="date"
              name="generatedDate"
              value={formData.generatedDate}
              onChange={handleChange}
            />
          </div>

          <div className="form-group">
            <label>File Type</label>
            <select
              name="fileType"
              value={formData.fileType}
              onChange={handleChange}
            >
              <option>PDF</option>
              <option>Excel</option>
              <option>CSV</option>
            </select>
          </div>

          <div className="modal-actions">
            <button
              type="button"
              className="btn-danger"
              onClick={() => navigate("/reports")}
            >
              Cancel
            </button>

            <button type="submit" className="btn-primary">
              Save Report
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};