import React, { useEffect, useState } from "react";
import { Plus, Filter, Edit, Trash2, Download, Loader2, FileText } from "lucide-react";
import type { ColumnDef } from "@tanstack/react-table";
import DataTable from "../components/DataTable";
import DeleteConfirmModal from "./modals/DeleteConfirmModal";
import { useNavigate } from "react-router-dom";
import { apiFetch } from "../utils/apiConfig";

interface Report {
  _id: string;
  reportName: string;
  reportType: string;
  generatedBy: string;
  locationFilter?: string;
  startDate: string;
  endDate: string;
  fileType: string;
  fileUrl?: string;
  status: string;
  createdAt?: string;
}

const formatDate = (value?: string) => {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleDateString();
};

export const ReportsView = () => {
  const navigate = useNavigate();

  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [reportToDelete, setReportToDelete] = useState<Report | null>(null);

  const loadReports = async () => {
    setLoading(true);
    setError("");
    try {
      const data = await apiFetch<Report[]>("/api/v1/reports?limit=100");
      setReports(data || []);
    } catch (err: any) {
      setError(err.message || "Failed to load Reports");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const openDeleteModal = (report: Report) => {
    setReportToDelete(report);
    setShowDeleteModal(true);
  };

  const handleDelete = async () => {
    if (!reportToDelete) return;

    try {
      await apiFetch(`/api/v1/reports/${reportToDelete._id}`, { method: "DELETE" });
      await loadReports();
    } catch (err: any) {
      setError(err.message || "Failed to delete Report");
    } finally {
      setReportToDelete(null);
      setShowDeleteModal(false);
    }
  };

  const columns: ColumnDef<Report>[] = [
    {
      accessorKey: "reportName",
      header: "Report Name",
      enableSorting: true,
    },
    {
      accessorKey: "reportType",
      header: "Report Type",
      enableSorting: true,
    },
    {
      accessorKey: "generatedBy",
      header: "Generated By",
      enableSorting: true,
    },
    {
      accessorKey: "locationFilter",
      header: "Location Filter",
      enableSorting: true,
      cell: ({ row }) => <span>{row.original.locationFilter || "-"}</span>,
    },
    {
      header: "Date Range",
      cell: ({ row }) => (
        <span>
          {formatDate(row.original.startDate)} to {formatDate(row.original.endDate)}
        </span>
      ),
    },
    {
      accessorKey: "createdAt",
      header: "Generated Date",
      enableSorting: true,
      cell: ({ row }) => <span>{formatDate(row.original.createdAt)}</span>,
    },
    {
      accessorKey: "fileType",
      header: "File Type",
      enableSorting: true,
    },
    {
      accessorKey: "status",
      header: "Status",
      enableSorting: false,
      cell: ({ row }) => (
        <span
          className={`status-badge ${
            row.original.status === "Generated"
              ? "status-active"
              : row.original.status === "Generating"
              ? "status-warning"
              : "status-inactive"
          }`}
        >
          {row.original.status}
        </span>
      ),
    },
    {
      header: "Download",
      cell: ({ row }) => (
        <button
          className="icon-btn"
          style={{ width: 28, height: 28 }}
          disabled={!row.original.fileUrl}
          onClick={() => row.original.fileUrl && window.open(row.original.fileUrl, "_blank")}
        >
          <Download size={14} />
        </button>
      ),
    },
    {
      header: "Actions",
      cell: ({ row }) => (
        <div style={{ display: "flex", gap: "8px" }}>
          <button
            className="icon-btn"
            style={{ width: 28, height: 28 }}
            onClick={() =>
              navigate("/reports/edit", {
                state: {
                  report: row.original,
                },
              })
            }
          >
            <Edit size={14} />
          </button>

          <button
            className="icon-btn"
            style={{ width: 28, height: 28 }}
            onClick={() => openDeleteModal(row.original)}
          >
            <Trash2 size={14} />
          </button>
        </div>
      ),
    },
  ];

  return (
    <>
      <div className="dashboard-area">
        <div className="page-header">
          <div className="page-title">
            <h1>Reports</h1>
            <p>Generate and manage system reports.</p>
          </div>

          <div style={{ display: "flex", gap: "12px" }}>
            <button className="icon-btn">
              <Filter size={18} />
            </button>

            <button
              className="btn-primary"
              onClick={() => navigate("/reports/add")}
            >
              <Plus size={18} />
              Generate Report
            </button>
          </div>
        </div>

        {error && (
          <div style={{ background: 'rgba(255, 61, 0, 0.1)', color: '#ff3d00', padding: '12px', borderRadius: '8px', marginBottom: '16px' }}>
            {error}
          </div>
        )}

        <div className="card">
          {loading ? (
            <div style={{ display: "flex", justifyContent: "center", padding: "40px" }}>
              <Loader2 size={24} className="spin" />
            </div>
          ) : reports.length === 0 ? (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "12px", padding: "60px 20px", textAlign: "center" }}>
              <FileText size={40} color="var(--text-secondary)" />
              <h3 style={{ margin: 0 }}>No reports yet</h3>
              <p style={{ margin: 0, color: "var(--text-secondary)" }}>
                Generate your first report to see it listed here.
              </p>
              <button className="btn-primary" onClick={() => navigate("/reports/add")}>
                <Plus size={16} />
                Generate first report
              </button>
            </div>
          ) : (
            <DataTable
              data={reports}
              columns={columns}
              searchPlaceholder="Search report name, type..."
            />
          )}
        </div>
      </div>

      <DeleteConfirmModal
        isOpen={showDeleteModal}
        onClose={() => {
          setShowDeleteModal(false);
          setReportToDelete(null);
        }}
        onConfirm={handleDelete}
        personName={reportToDelete?.reportName}
        title="Delete Report"
      />
    </>
  );
};
