import React, { useState } from "react";
import { Plus, Filter, Edit, Trash2, Eye, Download } from "lucide-react";
import DataTable from "../components/DataTable";
import DeleteConfirmModal from "./modals/DeleteConfirmModal";
import { useNavigate } from "react-router-dom";

interface Report {
  id: string;
  reportName: string;
  reportType: string;
  generatedBy: string;
  locationFilter: string;
  dateRange: string;
  generatedDate: string;
  fileType: string;
  status: string;
}

export const ReportsView = () => {
  const navigate = useNavigate();

  const [reports, setReports] = useState<Report[]>(
    Array.from({ length: 50 }, (_, i) => ({
      id: `REP-${String(i + 1).padStart(3, "0")}`,
      reportName: `Environment Report ${i + 1}`,
      reportType: i % 2 === 0 ? "Tree Report" : "Activity Report",
      generatedBy: `Admin ${i + 1}`,
      locationFilter: `District ${i + 1}`,
      dateRange: "01-02-2026 to 15-02-2026",
      generatedDate: "2026-02-15",
      fileType: i % 2 === 0 ? "PDF" : "Excel",
      status: "Generated",
    }))
  );

  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [reportToDelete, setReportToDelete] = useState<Report | null>(null);

  const openDeleteModal = (report: Report) => {
    setReportToDelete(report);
    setShowDeleteModal(true);
  };

  const handleDelete = () => {
    if (!reportToDelete) return;

    setReports((prev) =>
      prev.filter((report) => report.id !== reportToDelete.id)
    );

    setReportToDelete(null);
    setShowDeleteModal(false);
  };

  const columns: ColumnDef<Report>[] = [
    {
      accessorKey: "reportName",
      header: "Report Name",
      enableSorting: true,
    },
    {
      accessorKey: "reportType",
      header: "Report Type",
      enableSorting: true,
    },
    {
      accessorKey: "generatedBy",
      header: "Generated By",
      enableSorting: true,
    },
    {
      accessorKey: "locationFilter",
      header: "Location Filter",
      enableSorting: true,
    },
    {
      accessorKey: "dateRange",
      header: "Date Range",
      enableSorting: true,
    },
    {
      accessorKey: "generatedDate",
      header: "Generated Date",
      enableSorting: true,
    },
    {
      accessorKey: "fileType",
      header: "File Type",
      enableSorting: true,
    },
    {
      header: "Download",
      cell: () => (
        <button
          className="icon-btn"
          style={{ width: 28, height: 28 }}
        >
          <Download size={14} />
        </button>
      ),
    },
    {
      header: "Actions",
      cell: ({ row }) => (
        <div style={{ display: "flex", gap: "8px" }}>
          <button
            className="icon-btn"
            style={{ width: 28, height: 28 }}
          >
            <Eye size={14} />
          </button>

          <button
            className="icon-btn"
            style={{ width: 28, height: 28 }}
            onClick={() =>
              navigate("/reports/edit", {
                state: {
                  report: row.original,
                },
              })
            }
          >
            <Edit size={14} />
          </button>

          <button
            className="icon-btn"
            style={{ width: 28, height: 28 }}
            onClick={() => openDeleteModal(row.original)}
          >
            <Trash2 size={14} />
          </button>
        </div>
      ),
    },
  ];

  return (
    <>
      <div className="dashboard-area">
        <div className="page-header">
          <div className="page-title">
            <h1>Reports</h1>
            <p>Generate and manage system reports.</p>
          </div>

          <div style={{ display: "flex", gap: "12px" }}>
            <button className="icon-btn">
              <Filter size={18} />
            </button>

            <button
              className="btn-primary"
              onClick={() => navigate("/reports/add")}
            >
              <Plus size={18} />
              Generate Report
            </button>
          </div>
        </div>

        <div className="card">
          <DataTable
            data={reports}
            columns={columns}
            searchPlaceholder="Search report name, type..."
          />
        </div>
      </div>

      <DeleteConfirmModal
        isOpen={showDeleteModal}
        onClose={() => {
          setShowDeleteModal(false);
          setReportToDelete(null);
        }}
        onConfirm={handleDelete}
        personName={reportToDelete?.reportName}
      />
    </>
  );
};